//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma.ViewResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Firma.ViewResources.GlobalResources", typeof(GlobalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj Fakturę.
        /// </summary>
        internal static string Faktura {
            get {
                return ResourceManager.GetString("Faktura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faktury.
        /// </summary>
        internal static string FakturyWyswietl {
            get {
                return ResourceManager.GetString("FakturyWyswietl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj Pracownika.
        /// </summary>
        internal static string PracodwnikDodaj {
            get {
                return ResourceManager.GetString("PracodwnikDodaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pracownicy.
        /// </summary>
        internal static string PracownicyWyswietl {
            get {
                return ResourceManager.GetString("PracownicyWyswietl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj.
        /// </summary>
        internal static string PracownikEdytuj {
            get {
                return ResourceManager.GetString("PracownikEdytuj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowe Przyjęcie.
        /// </summary>
        internal static string Przyjęcie {
            get {
                return ResourceManager.GetString("Przyjęcie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj Towar.
        /// </summary>
        internal static string Towar {
            get {
                return ResourceManager.GetString("Towar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Towary.
        /// </summary>
        internal static string TowaryWyswietl {
            get {
                return ResourceManager.GetString("TowaryWyswietl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowe wydanie.
        /// </summary>
        internal static string Wydanie {
            get {
                return ResourceManager.GetString("Wydanie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj Wypłatę.
        /// </summary>
        internal static string Wyplata {
            get {
                return ResourceManager.GetString("Wyplata", resourceCulture);
            }
        }
    }
}
